config/routes.rb
Moovies::Application.routes.draw do

  match "angular_test" => "angular_test#index"

  match "renew_monthly_credits_for_a_la_carte" => "renew_monthly_subscription#renew_monthly_credits_for_a_la_carte"
  match "social_activation" => "social_activation#activate"
  match '/auth/:provider/callback' => 'authentications#create'
  match 'canvas' => 'authentications#canvas'

  concern :productable do
    resources :products, :only => :index
  end

  root to: 'products#index'

  resource :ogone, :only => [:create]
  resource :home_products, :only => [:update, :edit]
  resource :list, :only => [:new, :create]

  match 'flag' => 'home#flag'
  resources :prospects, :only => [:create, :new]
  scope '(:kind)', :kind => /normal|adult/ do
    localized do
      devise_for :customers, :controllers => {
        :registrations => "customers/registrations",
        :sessions => "customers/sessions"#,
        #:passwords => "customers/passwords"
      }
      resources :customers do
        match 'newsletter' => 'customers#newsletter', :only => [:update]
        resource 'addresses', :only => [:edit, :update, :create]
        resource 'suspension', :only => [:new, :create, :destroy]
        resource 'promotion', :only => [:show, :edit]
        resource 'images', :only => [:create]
        resource :payment_methods, :only => [:edit, :update, :show]
        resources :reviews, :only => [:index]
      end
      match 'info/:page_name' => 'info#index', :as => :info
      match 'streaming_products/sample', :to => 'streaming_products#sample'
      resources :streaming_products, :only => [:show] do
        match 'language' => 'streaming_products#language'
        match 'subtitle' => 'streaming_products#subtitle'
        match 'versions' => 'streaming_products#versions'
      end
      resources :products, :only => [:show], constraints: { :id => /[0-9]+[0-9a-zA-Z\-_]*/ }
      resources :products, :only => [], constraints: { :product_id => /[0-9]+[0-9a-zA-Z\-_]*/ } do
        resource :rating, :only => :create
        resources :reviews, :only => [:new, :create]
        #resources :tokens, :only => [:new, :create]
        match 'step' => 'products#step'
        match 'awards'=> 'products#awards'
        match 'seen' => 'products#seen'
        match 'trailer' => 'products#trailer'
        match 'uninterested' => 'products#uninterested'
        match 'action' => 'products#action'
        match 'log' => 'products#log'
        match 'data' => 'products#data'
        match 'sign_up' => 'products#sign_up'
      end
      match 'products(/:package)(/:view_mode)' => 'products#index', :as => :products_short
      resources :phone_requests, :only => [:new, :create, :index]
      resources :actors, :only => [:index], concerns: :productable
      resources :directors, :only => [], concerns: :productable
    end
  end

  root_path = 'products#index'

  scope ':locale/(:kind)', :locale => /en|fr|nl/, :kind => /normal|adult/ do
    match 'orangesmsconfirm' => 'orangeconfirm#promotion'
  	match "carrefourbonus" => "carrefourbonus#plans"
    match "freetrial" => "freetrial#plans"
    match "photobox" => "photobox#plans"
    match 'carrefour' => 'home#carrefour'
    match 'belgium' => "home#belgium"
    match 'halloween' => "halloween#collection"
    resource :public_promotion, :only => [:edit, :update]
    match "/" => 'products#index', :as => :root_localize
    match "validation" => 'home#validation'
    match 'customers/promotion' => "customers#promotion"
    devise_for :customers, :controllers => {
        :registrations => "customers/registrations",
        :confirmations => "customers/confirmations"#,
        #:passwords => "customers/passwords"
    }, :as => :old_customers
    resources :customers, :as => :old_customer do
      match 'newsletter' => 'customers#newsletter', :only => [:update]
      resource 'addresses', :only => [:edit, :update, :create]
      resource 'suspension', :only => [:new, :create, :destroy]
      resource 'promotion', :only => [:show, :edit]
      resource 'images', :only => [:create]
      resource :payment_methods, :only => [:edit, :update, :show]
      resources :reviews, :only => [:index]
    end
    match 'info/:page_name' => 'info#index', :as => :info_old

    resources :products, :only => [:index, :show], :as => :old_products do
      resource :rating, :only => :create
      resources :reviews, :only => [:new, :create]
      resources :tokens, :only => [:new, :create]
      match 'awards'=> 'products#awards'
      match 'seen' => 'products#seen'
      match 'trailer' => 'products#trailer'
      match 'uninterested' => 'products#uninterested'
      match 'action' => 'products#action'
      match 'log' => 'products#log'
    end
    resources :phone_requests, :only => [:new, :create, :index], :as => :old_phone_requests
    match 'search/(:search)' => 'search#index', :as => :search
    resources :public_newsletters, :only => [:new, :create]
    resources :reviews, :only => :show do
      resource :review_rating, :only => :create
    end
    match "messages/urgent" => "messages#urgent"
    resources :messages
    resources :tickets do
      resources :message_tickets, :only => [:create]
    end
    resources :promotions, :only => [:show]
    post 'promotions/:id' => "promotions#create", :as => :promotion_canva
    resource :subscription, :only => [:update]
    resources :categories, :only => [:index], concerns: :productable
    resources :actors, :only => [:index], concerns: :productable, :as => :old_actors
    resources :directors, :only => [], concerns: :productable, :as => :old_directors
    resources :studios, :only => [:index], concerns: :productable
    get 'faq', :to => 'messages#faq'

    resources :steps, :only => [:show, :update]
    resources :watchlists, :as => :vod_wishlists
    match 'display_vod' => 'watchlists#display_vod'
    resource :search_filters, :only => [:update, :destroy]
    match 'streaming_products/sample', :to => 'streaming_products#sample', :as => :old_streaming_products_sample
    resources :streaming_products, :only => [:show], :as => :old_streaming_products do
      match 'language' => 'streaming_products#language'
      match 'subtitle' => 'streaming_products#subtitle'
      match 'versions' => 'streaming_products#versions'
    end
    get 'unsubscribe', :to => 'customers#unsubscribe'
    get 'back_to_tvod', :to => 'customers#back_to_tvod'
    #match ':id' => "promotions#show", :as => :promotion_localize, constraints: lambda { |request| Promotion.find_by_name(request.path_parameters[:id]) || 'samsung' }
    get ':id' => "promotions#show", :as => :promotion_localize, :id => /samsung|promotion/
    post ':id' => "promotions#create", :as => :promotion_localize, :id => /samsung|promotion/

  end


  get ':id' => "promotions#show", defaults: { format: 'choose' }, :as => :promotion, :id => /smarttv|radio_contact|samsung|nostalgie|playstation/, :as => :short_promotion
  post ':id' => "promotions#show", defaults: { format: 'choose' }, :as => :promotion, :id => /smarttv|radio_contact|samsung|nostalgie/, :as => :short_promotion
  resources :promotions, defaults: { format: 'choose' }, :only => [:show], :as => :root_promotion

  match "/404", :to => "errors#not_found"
  match "/500", :to => "errors#not_found"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  #layout "application_old"

  def index
    @body_id = 'home'
    @meta_title = t("home.index.meta_title", :default => '')
    @meta_description = t("home.index.meta_description", :default => '')
    @new_svod = HomeProduct.where(:country => Product.country_short_name(session[:country_id]), :kind => "svod#{params[:kind] == :adult ? '_adult' : ''}", :locale_id => Moovies.languages[I18n.locale]).order('id asc').includes(:product => [Product.get_vod_online_name(session[:country_id]),"descriptions_#{I18n.locale}", :svod_dates])
    @new_tvod = HomeProduct.where(:country => Product.country_short_name(session[:country_id]), :kind => "tvod#{params[:kind] == :adult ? '_adult' : ''}", :locale_id => Moovies.languages[I18n.locale]).order('id asc').includes(:product => [Product.get_vod_online_name(session[:country_id]),"descriptions_#{I18n.locale}", :svod_dates])
    @discount_bottom = Discount.find(Moovies.discount["hp_bottom_#{I18n.locale}_#{params[:kind]}"])
    @newsletter = PublicNewsletter.new(params[:public_newsletter])
    @svod_id = params[:kind] == :adult ? 4 : 1
    @tvod_id = params[:kind] == :adult ? 5 : 2
    @carousel = Landing.by_language(I18n.locale).not_expirated.order_id
    if current_customer
      @carousel = params[:kind] == :adult ? @carousel.adult : @carousel.private
      @vod_wishlist = current_customer.products.collect(&:products_id)
    else
      @carousel = params[:kind] == :adult ? @carousel.adult_public : @carousel.public
    end
  end

  def validation
    if params[:valid] == "1"
      session[:adult] = 1
      begin
        redirect_to session['current_uri']
      rescue => e
        redirect_to root_localize_path
      end
    end
  end

  def flag
    if !params['mail_id'].nil?
      histo = MailHistory.find(params['mail_id'])
      histo.update_attributes(:mail_opened => histo.mail_opened + 1, :mail_opened_date => Time.now)
      MessageTicket.find_by_mail_history_id(params['mail_id']).update_attributes(:is_read => 1)
    end
    #render :text => open('app/assets/images/blank.gif', "rb").read
  end

  def moodme
  end

  def carrefour
    if customer_signed_in?
      gon.carrefour_activation_code = params[:carrefour_activation_code]
      customer = current_customer
      #@hide_menu = true
      @body_id = 'carrefour'
      @error_abo = false
      @error_code = false
      @error_discount_reused = false
      if request.post?
        if params[:abo].blank? || ![7,8,9,10,11].include?(params[:abo].to_i)
          @error_abo = true
        end
        if params[:abo] === "7"
          activation = Activation.find_by_activation_code(params[:carrefour_code])
          discount = Discount.find_by_discount_code("CFB2FILMS")
          if !customer.discount_reuse?(discount.month_before_reuse)
            @error_discount_reused = true
          else
            customer.tvod_free = customer.tvod_free + discount.tvod_free
            customer.abo_history(38, customer.abo_type_id, discount.to_param)
            customer.code = "CFB2FILMS"
            customer.step = discount.goto_step
            customer.customers_abo = 1
            if customer.save!
              if DiscountUse.create(:discount_code_id => discount.id, :customer_id => customer.to_param, :discount_use_date => Time.now)
                if activation.update_attributes(:customers_id => customer.to_param, :created_at => Time.now.localtime)
                  redirect_to root_path
                end
              end
            end
          end
        elsif params[:abo] === "8"
          activation = Activation.find_by_activation_code(params[:carrefour_code])
          discount = Discount.find_by_discount_code("CFB4FILMS")
          if !customer.discount_reuse?(discount.month_before_reuse)
            @error_discount_reused = true
          else
            customer.tvod_free = customer.tvod_free + discount.tvod_free
            customer.abo_history(38, customer.abo_type_id, discount.to_param)
            customer.code = "CFB4FILMS"
            customer.step = discount.goto_step
            customer.customers_abo = 1
            if customer.save!
              if DiscountUse.create(:discount_code_id => discount.id, :customer_id => customer.to_param, :discount_use_date => Time.now)
                if activation.update_attributes(:customers_id => customer.to_param, :created_at => Time.now.localtime)
                  redirect_to root_path
                end
              end
            end
          end
        elsif params[:abo] === "9"
          activation = Activation.find_by_activation_code(params[:carrefour_code])
          discount = Discount.find_by_discount_code("CFB6FILMS")
          if !customer.discount_reuse?(discount.month_before_reuse)
            @error_discount_reused = true
          else
            customer.tvod_free = customer.tvod_free + discount.tvod_free
            customer.abo_history(38, customer.abo_type_id, discount.to_param)
            customer.code = "CFB6FILMS"
            customer.step = discount.goto_step
            customer.customers_abo = 1
            if customer.save!
              if DiscountUse.create(:discount_code_id => discount.id, :customer_id => customer.to_param, :discount_use_date => Time.now)
                if activation.update_attributes(:customers_id => customer.to_param, :created_at => Time.now.localtime)
                  redirect_to root_path
                end
              end
            end
          end
        elsif params[:abo] === "10"
          activation = Activation.find_by_activation_code(params[:carrefour_code])
          discount = Discount.find_by_discount_code("CFB8FILMS")
          if !customer.discount_reuse?(discount.month_before_reuse)
            @error_discount_reused = true
          else
            customer.tvod_free = customer.tvod_free + discount.tvod_free
            customer.abo_history(38, customer.abo_type_id, discount.to_param)
            customer.code = "CFB8FILMS"
            customer.step = discount.goto_step
            customer.customers_abo = 1
            if customer.save!
              if DiscountUse.create(:discount_code_id => discount.id, :customer_id => customer.to_param, :discount_use_date => Time.now)
                if activation.update_attributes(:customers_id => customer.to_param, :created_at => Time.now.localtime)
                  redirect_to root_path
                end
              end
            end
          end
        elsif params[:abo] === "11"
          activation = Activation.find_by_activation_code(params[:carrefour_code])
          discount = Discount.find_by_discount_code("CFB10FILMS")
          if !customer.discount_reuse?(discount.month_before_reuse)
            @error_discount_reused = true
          else
            customer.tvod_free = customer.tvod_free + discount.tvod_free
            customer.abo_history(38, customer.abo_type_id, discount.to_param)
            customer.code = "CFB10FILMS"
            customer.step = discount.goto_step
            customer.customers_abo = 1
            if customer.save!
              if DiscountUse.create(:discount_code_id => discount.id, :customer_id => customer.to_param, :discount_use_date => Time.now)
                if activation.update_attributes(:customers_id => customer.to_param, :created_at => Time.now.localtime)
                  redirect_to root_path
                end
              end
            end
          end
        end
      end
    else
      @hide_menu = true
      @body_id = 'carrefour'
      @error_abo = false
        @error_code = false
      if request.post?
        if params[:abo].blank? || ![7,8,9,10,11].include?(params[:abo].to_i)
          @error_abo = true
        end
        if params[:abo] === "7"
          redirect_to new_customer_session_path( :activation => params[:carrefour_code], :code => "CFB2FILMS")
        elsif params[:abo] === "8"
          redirect_to new_customer_session_path( :activation => params[:carrefour_code], :code => "CFB4FILMS")
        elsif params[:abo] === "9"
          redirect_to new_customer_session_path( :activation => params[:carrefour_code], :code => "CFB6FILMS")
        elsif params[:abo] === "10"
          redirect_to new_customer_session_path( :activation => params[:carrefour_code], :code => "CFB8FILMS")
        elsif params[:abo] === "11"
          redirect_to new_customer_session_path( :activation => params[:carrefour_code], :code => "CFB10FILMS")
        elsif params[:carrefour_code].present? && params[:carrefour_code] != "CARREFOUR"
          activation = Activation.by_name(params[:carrefour_code]).available.first
          unless activation
            @error_code = true
          end
        elsif
          @error_code = true
        end
        #if @error_code == false && @error_abo == false && params[:carrefour_code] != "CARREFOUR"
        #  redirect_to new_customer_session_path( :code => params[:carrefour_code], :abo => params[:abo]) and return
        #end
      end
    end
  end

  def belgium
    @body_id = 'products_index'
    @body_class = 'reload'
    @countries = ProductCountry.visible.ordered
    per_page = params[:format] == 'json' ? 5000 : 50
    new_params = session[:sexuality] == 0 ? params.merge(:per_page => per_page, :country_id => session[:country_id], :hetero => 1, :includes => ["descriptions_#{I18n.locale}", 'vod_online_be']) : params.merge(:per_page => 50, :country_id => session[:country_id], :includes => ["descriptions_#{I18n.locale}", 'vod_online_be'])
    tvod_package_id = params[:kind] == :adult ? 5 : 2
    svod_package_id = params[:kind] == :adult ? 4 : 1

    respond_to do |format|
      format.html do
        @country =        Product.filter(nil, new_params.merge(:belgium => 1,  :package => Moovies.packages.invert[tvod_package_id]))
        @actor =          Product.filter(nil, new_params.merge(:belgium => 2,  :package => Moovies.packages.invert[tvod_package_id]))

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index/_carousel.html.erb
<% path =  carousel_path(carousel) %>
<% image = image_tag(carousel.image, :alt => carousel.title(I18n.locale), :size => '932x328') %>
<div id="slider-wrap">
  <div id="image_promo">
    <h1><%= t('.title').html_safe %></h1>
    <h2><%= t('.slogan').html_safe %></h2>
    <ul id="output">
      <li>
        <div class="caption osc">
          <h2><%= carousel.title(I18n.locale) %></h2>
          <h4>
            <%= carousel.description(I18n.locale) %>
          </h4>
        </div>
        <a href="<%= path %>"><%= image %></a>
      </li>
    </ul>
  </div>
</div>

app/views/home/index/_carousel_adult.html.erb
<div id="slider-wrap">
  <div id="image_promo">
    <h1><%= t('home.index.title').html_safe %></h1>
    <h2><%= t 'home.index.slogan' %></h2>
    <ul id="output">
      <li>
        <div id="try_it">
          <%= link_to t('.try'), info_path(:page_name => t('routes.infos.params.abo')), :class => 'essaigratuit osc btn' %> 
        </div>
        <%= link_to image_tag("#{I18n.locale}/unlimited-video-on-demand-adult2.jpg", :size => '932x328'), info_path(:page_name => t('routes.infos.params.abo')) %>
      </li>
    </ul>
  </div>
</div>
<!-- #slider-wrap -->

app/views/home/index/_carousel_public.html.erb
<div id="slider-wrap">
  
  <div id="image_promo">
    <div id="try_it" align="center">
      <% if current_customer %>
        <h1><%= t(".carousel_h1_logged_#{params[:kind]}").html_safe %></h1>
        <h2><%= t(".carousel_h2_logged_#{params[:kind]}").html_safe %></h2>
        <%= link_to t('home.index.try_logged'), products_short_path(), :class => 'essaigratuit osc btn' %>
      <% else %>
        <h1><%= t(".carousel_h1_#{params[:kind]}").html_safe %></h1>
        <h2><%= t(".carousel_h2_#{params[:kind]}").html_safe %></h2>
        <%= link_to t('home.index.try'), new_customer_registration_path(:code => get_code(@discount_top.name)), :class => 'essaigratuit osc btn' %> 
        <div id="engagement"><%= t 'home.index.try_text' %></div>
     <% end %>
    </div>
    <ul id="output">
      <%= render :partial => 'home/index/carousel_public_item', :collection => @carousel %>
    </ul>
    <div id='select'>
     <div id="prev"></div> 
     <div id="next"></div> 
    </div>
  </div>
</div>
<!-- #slider-wrap -->

app/views/home/index/_carousel_public_item.html.erb
<% key = current_customer && current_customer.tvod_free > 0 ? '.withouy_price' : '.price' %>
<% if carousel_public_item.product.get_vod_online(session[:country_id]).first %>
  <% path =  carousel_path(carousel_public_item, true) %>
  <% image = image_tag(carousel_public_item.image, :alt => carousel_public_item.product.title, :size => '585x328') %>
  <li>
    <a href="<%= path %>" class="regarder"><%= t(key, :price => carousel_public_item.product.get_vod_online(session[:country_id]).first.ppv_price).html_safe %></a>
    <a href="<%= path %>" class="image">
      <%= image %>
    </a>
    <div class="caption osc">
      <h2><a href="<%= path %>"><%= carousel_public_item.product.title %></a></h2>
    </div>
  </li>
<% end %>

app/views/home/index/_lists.html.erb
<div id="slider-view" class="block100">
  <div class="home-carousel-holder center-block">
    <div class="hr-with-words">
      <span class="Arial f30 light-blue"><%= params[:kind] == :adult ? t('home.index.tvod_adult_new').html_safe : t('home.index.tvod_new').html_safe %></span>
    </div>
    <section class="responsive-carousel slider">
      <%= render :partial => 'products/detail', :collection => @new_tvod, :locals => {:source => type = 'subscription' ? @wishlist_source[:subscription] : @wishlist_source[:hp_list]} %>
    </section>
  </div>
</div>
<div class="block100 text-center mart40">
  <%= link_to products_short_path(:package => t("routes.product.params.package.#{Moovies.packages.invert[params[:kind] == :adult ? 5 : 2]}"), :tag => 3), :class => "f25" do %>
      <i class="fa fa-play f15"></i> <%= t('home.index.all') %>
  <% end %>
</div>

app/views/home/index/_promo_film.html.erb
<!-- movie Free-->
<div id="movie-free">
  <div class="movie"><a href="<%= promotion_path(:id => 'film-site')%>"><img src="http://www.dvdpost.be/images/plush/movie_free/129693.jpg" alt='<%= t('.promo_film_title').html_safe %>' /></a></div>
  <div class="text-explain">
    <h1><%= t('.promo_film_title').html_safe %></h1>
    <h2><%= t('.promo_film_desc').html_safe %></h2>
    <p align="right">
      <%= link_to t('.promo_film_btn'), promotion_path(:id => 'film-site'), :class => 'filmgratuit osc btn' %>
    </p>
  </div>
  <div class="clearfix"></div>
</div>
<!-- Services -->