config/routes.rb
Moovies::Application.routes.draw do

  match "angular_test" => "angular_test#index"

  match "renew_monthly_credits_for_a_la_carte" => "renew_monthly_subscription#renew_monthly_credits_for_a_la_carte"
  match "social_activation" => "social_activation#activate"
  match '/auth/:provider/callback' => 'authentications#create'
  match 'canvas' => 'authentications#canvas'

  concern :productable do
    resources :products, :only => :index
  end

  root to: 'products#index'

  resource :ogone, :only => [:create]
  resource :home_products, :only => [:update, :edit]
  resource :list, :only => [:new, :create]

  match 'flag' => 'home#flag'
  resources :prospects, :only => [:create, :new]
  scope '(:kind)', :kind => /normal|adult/ do
    localized do
      devise_for :customers, :controllers => {
        :registrations => "customers/registrations",
        :sessions => "customers/sessions"#,
        #:passwords => "customers/passwords"
      }
      resources :customers do
        match 'newsletter' => 'customers#newsletter', :only => [:update]
        resource 'addresses', :only => [:edit, :update, :create]
        resource 'suspension', :only => [:new, :create, :destroy]
        resource 'promotion', :only => [:show, :edit]
        resource 'images', :only => [:create]
        resource :payment_methods, :only => [:edit, :update, :show]
        resources :reviews, :only => [:index]
      end
      match 'info/:page_name' => 'info#index', :as => :info
      match 'streaming_products/sample', :to => 'streaming_products#sample'
      resources :streaming_products, :only => [:show] do
        match 'language' => 'streaming_products#language'
        match 'subtitle' => 'streaming_products#subtitle'
        match 'versions' => 'streaming_products#versions'
      end
      resources :products, :only => [:show], constraints: { :id => /[0-9]+[0-9a-zA-Z\-_]*/ }
      resources :products, :only => [], constraints: { :product_id => /[0-9]+[0-9a-zA-Z\-_]*/ } do
        resource :rating, :only => :create
        resources :reviews, :only => [:new, :create]
        #resources :tokens, :only => [:new, :create]
        match 'step' => 'products#step'
        match 'awards'=> 'products#awards'
        match 'seen' => 'products#seen'
        match 'trailer' => 'products#trailer'
        match 'uninterested' => 'products#uninterested'
        match 'action' => 'products#action'
        match 'log' => 'products#log'
        match 'data' => 'products#data'
        match 'sign_up' => 'products#sign_up'
      end
      match 'products(/:package)(/:view_mode)' => 'products#index', :as => :products_short
      resources :phone_requests, :only => [:new, :create, :index]
      resources :actors, :only => [:index], concerns: :productable
      resources :directors, :only => [], concerns: :productable
    end
  end

  root_path = 'products#index'

  scope ':locale/(:kind)', :locale => /en|fr|nl/, :kind => /normal|adult/ do
    match 'orangesmsconfirm' => 'orangeconfirm#promotion'
  	match "carrefourbonus" => "carrefourbonus#plans"
    match "freetrial" => "freetrial#plans"
    match "photobox" => "photobox#plans"
    match 'carrefour' => 'home#carrefour'
    match 'belgium' => "home#belgium"
    match 'halloween' => "halloween#collection"
    resource :public_promotion, :only => [:edit, :update]
    match "/" => 'products#index', :as => :root_localize
    match "validation" => 'home#validation'
    match 'customers/promotion' => "customers#promotion"
    devise_for :customers, :controllers => {
        :registrations => "customers/registrations",
        :confirmations => "customers/confirmations"#,
        #:passwords => "customers/passwords"
    }, :as => :old_customers
    resources :customers, :as => :old_customer do
      match 'newsletter' => 'customers#newsletter', :only => [:update]
      resource 'addresses', :only => [:edit, :update, :create]
      resource 'suspension', :only => [:new, :create, :destroy]
      resource 'promotion', :only => [:show, :edit]
      resource 'images', :only => [:create]
      resource :payment_methods, :only => [:edit, :update, :show]
      resources :reviews, :only => [:index]
    end
    match 'info/:page_name' => 'info#index', :as => :info_old

    resources :products, :only => [:index, :show], :as => :old_products do
      resource :rating, :only => :create
      resources :reviews, :only => [:new, :create]
      resources :tokens, :only => [:new, :create]
      match 'awards'=> 'products#awards'
      match 'seen' => 'products#seen'
      match 'trailer' => 'products#trailer'
      match 'uninterested' => 'products#uninterested'
      match 'action' => 'products#action'
      match 'log' => 'products#log'
    end
    resources :phone_requests, :only => [:new, :create, :index], :as => :old_phone_requests
    match 'search/(:search)' => 'search#index', :as => :search
    resources :public_newsletters, :only => [:new, :create]
    resources :reviews, :only => :show do
      resource :review_rating, :only => :create
    end
    match "messages/urgent" => "messages#urgent"
    resources :messages
    resources :tickets do
      resources :message_tickets, :only => [:create]
    end
    resources :promotions, :only => [:show]
    post 'promotions/:id' => "promotions#create", :as => :promotion_canva
    resource :subscription, :only => [:update]
    resources :categories, :only => [:index], concerns: :productable
    resources :actors, :only => [:index], concerns: :productable, :as => :old_actors
    resources :directors, :only => [], concerns: :productable, :as => :old_directors
    resources :studios, :only => [:index], concerns: :productable
    get 'faq', :to => 'messages#faq'

    resources :steps, :only => [:show, :update]
    resources :watchlists, :as => :vod_wishlists
    match 'display_vod' => 'watchlists#display_vod'
    resource :search_filters, :only => [:update, :destroy]
    match 'streaming_products/sample', :to => 'streaming_products#sample', :as => :old_streaming_products_sample
    resources :streaming_products, :only => [:show], :as => :old_streaming_products do
      match 'language' => 'streaming_products#language'
      match 'subtitle' => 'streaming_products#subtitle'
      match 'versions' => 'streaming_products#versions'
    end
    get 'unsubscribe', :to => 'customers#unsubscribe'
    get 'back_to_tvod', :to => 'customers#back_to_tvod'
    #match ':id' => "promotions#show", :as => :promotion_localize, constraints: lambda { |request| Promotion.find_by_name(request.path_parameters[:id]) || 'samsung' }
    get ':id' => "promotions#show", :as => :promotion_localize, :id => /samsung|promotion/
    post ':id' => "promotions#create", :as => :promotion_localize, :id => /samsung|promotion/

  end


  get ':id' => "promotions#show", defaults: { format: 'choose' }, :as => :promotion, :id => /smarttv|radio_contact|samsung|nostalgie|playstation/, :as => :short_promotion
  post ':id' => "promotions#show", defaults: { format: 'choose' }, :as => :promotion, :id => /smarttv|radio_contact|samsung|nostalgie/, :as => :short_promotion
  resources :promotions, defaults: { format: 'choose' }, :only => [:show], :as => :root_promotion

  match "/404", :to => "errors#not_found"
  match "/500", :to => "errors#not_found"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  #layout "application_old"

  def index
    @body_id = 'home'
    @meta_title = t("home.index.meta_title", :default => '')
    @meta_description = t("home.index.meta_description", :default => '')
    @new_svod = HomeProduct.where(:country => Product.country_short_name(session[:country_id]), :kind => "svod#{params[:kind] == :adult ? '_adult' : ''}", :locale_id => Moovies.languages[I18n.locale]).order('id asc').includes(:product => [Product.get_vod_online_name(session[:country_id]),"descriptions_#{I18n.locale}", :svod_dates])
    @new_tvod = HomeProduct.where(:country => Product.country_short_name(session[:country_id]), :kind => "tvod#{params[:kind] == :adult ? '_adult' : ''}", :locale_id => Moovies.languages[I18n.locale]).order('id asc').includes(:product => [Product.get_vod_online_name(session[:country_id]),"descriptions_#{I18n.locale}", :svod_dates])
    @discount_bottom = Discount.find(Moovies.discount["hp_bottom_#{I18n.locale}_#{params[:kind]}"])
    @newsletter = PublicNewsletter.new(params[:public_newsletter])
    @svod_id = params[:kind] == :adult ? 4 : 1
    @tvod_id = params[:kind] == :adult ? 5 : 2
    @carousel = Landing.by_language(I18n.locale).not_expirated.order_id
    if current_customer
      @carousel = params[:kind] == :adult ? @carousel.adult : @carousel.private
      @vod_wishlist = current_customer.products.collect(&:products_id)
    else
      @carousel = params[:kind] == :adult ? @carousel.adult_public : @carousel.public
    end
  end

  def validation
    if params[:valid] == "1"
      session[:adult] = 1
      begin
        redirect_to session['current_uri']
      rescue => e
        redirect_to root_localize_path
      end
    end
  end

  def flag
    if !params['mail_id'].nil?
      histo = MailHistory.find(params['mail_id'])
      histo.update_attributes(:mail_opened => histo.mail_opened + 1, :mail_opened_date => Time.now)
      MessageTicket.find_by_mail_history_id(params['mail_id']).update_attributes(:is_read => 1)
    end
    #render :text => open('app/assets/images/blank.gif', "rb").read
  end

  def moodme
  end

  def carrefour
    if customer_signed_in?
      gon.carrefour_activation_code = params[:carrefour_activation_code]
      customer = current_customer
      #@hide_menu = true
      @body_id = 'carrefour'
      @error_abo = false
      @error_code = false
      @error_discount_reused = false
      if request.post?
        if params[:abo].blank? || ![7,8,9,10,11].include?(params[:abo].to_i)
          @error_abo = true
        end
        if params[:abo] === "7"
          activation = Activation.find_by_activation_code(params[:carrefour_code])
          discount = Discount.find_by_discount_code("CFB2FILMS")
          if !customer.discount_reuse?(discount.month_before_reuse)
            @error_discount_reused = true
          else
            customer.tvod_free = customer.tvod_free + discount.tvod_free
            customer.abo_history(38, customer.abo_type_id, discount.to_param)
            customer.code = "CFB2FILMS"
            customer.step = discount.goto_step
            customer.customers_abo = 1
            if customer.save!
              if DiscountUse.create(:discount_code_id => discount.id, :customer_id => customer.to_param, :discount_use_date => Time.now)
                if activation.update_attributes(:customers_id => customer.to_param, :created_at => Time.now.localtime)
                  redirect_to root_path
                end
              end
            end
          end
        elsif params[:abo] === "8"
          activation = Activation.find_by_activation_code(params[:carrefour_code])
          discount = Discount.find_by_discount_code("CFB4FILMS")
          if !customer.discount_reuse?(discount.month_before_reuse)
            @error_discount_reused = true
          else
            customer.tvod_free = customer.tvod_free + discount.tvod_free
            customer.abo_history(38, customer.abo_type_id, discount.to_param)
            customer.code = "CFB4FILMS"
            customer.step = discount.goto_step
            customer.customers_abo = 1
            if customer.save!
              if DiscountUse.create(:discount_code_id => discount.id, :customer_id => customer.to_param, :discount_use_date => Time.now)
                if activation.update_attributes(:customers_id => customer.to_param, :created_at => Time.now.localtime)
                  redirect_to root_path
                end
              end
            end
          end
        elsif params[:abo] === "9"
          activation = Activation.find_by_activation_code(params[:carrefour_code])
          discount = Discount.find_by_discount_code("CFB6FILMS")
          if !customer.discount_reuse?(discount.month_before_reuse)
            @error_discount_reused = true
          else
            customer.tvod_free = customer.tvod_free + discount.tvod_free
            customer.abo_history(38, customer.abo_type_id, discount.to_param)
            customer.code = "CFB6FILMS"
            customer.step = discount.goto_step
            customer.customers_abo = 1
            if customer.save!
              if DiscountUse.create(:discount_code_id => discount.id, :customer_id => customer.to_param, :discount_use_date => Time.now)
                if activation.update_attributes(:customers_id => customer.to_param, :created_at => Time.now.localtime)
                  redirect_to root_path
                end
              end
            end
          end
        elsif params[:abo] === "10"
          activation = Activation.find_by_activation_code(params[:carrefour_code])
          discount = Discount.find_by_discount_code("CFB8FILMS")
          if !customer.discount_reuse?(discount.month_before_reuse)
            @error_discount_reused = true
          else
            customer.tvod_free = customer.tvod_free + discount.tvod_free
            customer.abo_history(38, customer.abo_type_id, discount.to_param)
            customer.code = "CFB8FILMS"
            customer.step = discount.goto_step
            customer.customers_abo = 1
            if customer.save!
              if DiscountUse.create(:discount_code_id => discount.id, :customer_id => customer.to_param, :discount_use_date => Time.now)
                if activation.update_attributes(:customers_id => customer.to_param, :created_at => Time.now.localtime)
                  redirect_to root_path
                end
              end
            end
          end
        elsif params[:abo] === "11"
          activation = Activation.find_by_activation_code(params[:carrefour_code])
          discount = Discount.find_by_discount_code("CFB10FILMS")
          if !customer.discount_reuse?(discount.month_before_reuse)
            @error_discount_reused = true
          else
            customer.tvod_free = customer.tvod_free + discount.tvod_free
            customer.abo_history(38, customer.abo_type_id, discount.to_param)
            customer.code = "CFB10FILMS"
            customer.step = discount.goto_step
            customer.customers_abo = 1
            if customer.save!
              if DiscountUse.create(:discount_code_id => discount.id, :customer_id => customer.to_param, :discount_use_date => Time.now)
                if activation.update_attributes(:customers_id => customer.to_param, :created_at => Time.now.localtime)
                  redirect_to root_path
                end
              end
            end
          end
        end
      end
    else
      @hide_menu = true
      @body_id = 'carrefour'
      @error_abo = false
        @error_code = false
      if request.post?
        if params[:abo].blank? || ![7,8,9,10,11].include?(params[:abo].to_i)
          @error_abo = true
        end
        if params[:abo] === "7"
          redirect_to new_customer_session_path( :activation => params[:carrefour_code], :code => "CFB2FILMS")
        elsif params[:abo] === "8"
          redirect_to new_customer_session_path( :activation => params[:carrefour_code], :code => "CFB4FILMS")
        elsif params[:abo] === "9"
          redirect_to new_customer_session_path( :activation => params[:carrefour_code], :code => "CFB6FILMS")
        elsif params[:abo] === "10"
          redirect_to new_customer_session_path( :activation => params[:carrefour_code], :code => "CFB8FILMS")
        elsif params[:abo] === "11"
          redirect_to new_customer_session_path( :activation => params[:carrefour_code], :code => "CFB10FILMS")
        elsif params[:carrefour_code].present? && params[:carrefour_code] != "CARREFOUR"
          activation = Activation.by_name(params[:carrefour_code]).available.first
          unless activation
            @error_code = true
          end
        elsif
          @error_code = true
        end
        #if @error_code == false && @error_abo == false && params[:carrefour_code] != "CARREFOUR"
        #  redirect_to new_customer_session_path( :code => params[:carrefour_code], :abo => params[:abo]) and return
        #end
      end
    end
  end

  def belgium
    @body_id = 'products_index'
    @body_class = 'reload'
    @countries = ProductCountry.visible.ordered
    per_page = params[:format] == 'json' ? 5000 : 50
    new_params = session[:sexuality] == 0 ? params.merge(:per_page => per_page, :country_id => session[:country_id], :hetero => 1, :includes => ["descriptions_#{I18n.locale}", 'vod_online_be']) : params.merge(:per_page => 50, :country_id => session[:country_id], :includes => ["descriptions_#{I18n.locale}", 'vod_online_be'])
    tvod_package_id = params[:kind] == :adult ? 5 : 2
    svod_package_id = params[:kind] == :adult ? 4 : 1

    respond_to do |format|
      format.html do
        @country =        Product.filter(nil, new_params.merge(:belgium => 1,  :package => Moovies.packages.invert[tvod_package_id]))
        @actor =          Product.filter(nil, new_params.merge(:belgium => 2,  :package => Moovies.packages.invert[tvod_package_id]))

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/belgium.html.erb
<div class="container" id="content-left-right">
  <div class="content-left">
    <%= render :partial => 'products/index/filters_online', :locals => {:countries => @countries} %>
  </div>
  <div class="content-right">
    <div id="main-content" class="block100 movies">
      <div id="slider-view">
        <div class="home-carousel-holder center-block">
          <div class="hr-with-words">
            <span class="Arial f30 <%= params[:kind] == :adult ? "light-violet" : "light-blue" %>"><%= t('.belgium') %></span>
            <%= render :partial => 'products/index/hp_list', :locals => {:data => @country, :title => :country, :type => nil, :view_mode => nil, :source => 72, :belgium => 1} %>
            <%= render :partial => 'products/index/hp_list', :locals => {:data => @actor, :title => :actor, :type => nil, :view_mode => nil, :source => 73, :belgium => 2} %>
            <%= render :partial => 'products/index/hp_list', :locals => {:data => @director, :title => :director, :type => nil, :view_mode => nil, :source => 74, :belgium => 3} %>
            <%= render :partial => 'products/index/hp_list', :locals => {:data => @land, :title => :land, :type => nil, :view_mode => nil, :source => 75, :belgium => 4} %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/carrefour.html.erb
<div class="container white-bck dark-gray padb20">
  <h1 class="OpenSansCondensed f30 green pad0 mar0 mart10"><%= t('.offer') %></h1>
  <%= image_tag "template/carrefour-logo.png", class: "mart20" %>
  <p class="block100 martb20"><%= t('.customer').html_safe %></p>
  <p class="block100 carrefour-bullet"><%= t('.4loc').html_safe %></p>
  <p class="block100 carrefour-bullet"><%= t('.first').html_safe %></p>
  <%= form_tag carrefour_path(), :id => 'form_carrefour' do %>
      <h2 class="mart30 f20 bold block100"><%= t('.choose_formula') %></h2>
      <ul class="carrefour-list">
        <li class="text-center radius4">
          <h3 class="Arial">2 <%= t('.films') %></h3>
          <div class="carrefour-card-section block100">
            <span class="orange bold block100">0€</span>
            <%= t('.first_month') %>
          </div>
          <div class="carrefour-card-section block100">
            <span class="block100">3,99€</span>
            <span class="block100 f15"><%= t('.next_month') %></span>
          </div>
          <div class="carrefour-card-section block100">
            <input type="radio" class="iradio" id="carrefour-select-offer-2" name="abo" value='7' <%= "checked='checked'" if params[:abo]== "7" %>/>
          </div>
        </li>
        <li class="text-center radius4">
          <h3 class="Arial">4 <%= t('.films') %></h3>
          <div class="carrefour-card-section block100">
            <span class="orange bold block100">3,99€</span>
            <%= t('.first_month') %>
          </div>
          <div class="carrefour-card-section block100">
            <span class="block100">7,99€</span>
            <span class="block100 f15"><%= t('.next_month') %></span>
          </div>
          <div class="carrefour-card-section block100">
            <input type="radio" class="iradio" id="carrefour-select-offer-4" name="abo" value='8' <%= "checked='checked'" if params[:abo]== "8" %>/>
          </div>
        </li>
        <li class="text-center radius4">
          <h3 class="Arial">6 <%= t('.films') %></h3>
          <div class="carrefour-card-section block100">
            <span class="orange bold block100">7,99€</span>
            <%= t('.first_month') %>
          </div>
          <div class="carrefour-card-section block100">
            <span class="block100">11,99€</span>
            <span class="block100 f15"><%= t('.next_month') %></span>
          </div>
          <div class="carrefour-card-section block100">
            <input type="radio" class="iradio" id="carrefour-select-offer-6" name="abo" value='9' <%= "checked='checked'" if params[:abo] == "9" %>/>
          </div>
        </li>
        <li class="text-center radius4 most-popular">
          <h3 class="Arial">8 <%= t('.films') %></h3>
          <div class="carrefour-card-section block100">
            <span class="orange bold block100">10,99€</span>
            <%= t('.first_month') %>
          </div>
          <div class="carrefour-card-section block100">
            <span class="block100">14,99€</span>
            <span class="block100 f15"><%= t('.next_month') %></span>
          </div>
          <div class="carrefour-card-section block100">
            <input type="radio" class="iradio" id="carrefour-select-offer-8" name="abo" value='10' <%= "checked='checked'" if params[:abo] == "10" %>/>
          </div>
        </li>
        <li class="text-center radius4">
          <h3 class="Arial">10 <%= t('.films') %></h3>
          <div class="carrefour-card-section block100">
            <span class="orange bold block100">13,99€</span>
            <%= t('.first_month') %>
          </div>
          <div class="carrefour-card-section block100">
            <span class="block100">17,99€</span>
            <span class="block100 f15"><%= t('.next_month') %></span>
          </div>
          <div class="carrefour-card-section block100">
            <input type="radio" class="iradio" id="carrefour-select-offer-10" name="abo" value='11' <%= "checked='checked'" if params[:abo] == "11" %>/>
          </div>
        </li>
      </ul>
      <ul class="cl-list block100 mart30">
        <li><%= t('.catalog').html_safe %></li>
        <li><%= t('.free').html_safe %></li>
        <li><%= t('.increase').html_safe %></li>
        <li><%= t('.2_credits').html_safe %></li>
      </ul>
      <h2 class="mart30 f20 bold block100"><%= t('.fill_in_code') %></h2>
      <div class="block100">
        <% if @error_abo %>
            <div class="alert alert-danger">
              <strong><%= t('.abo_error') %></strong>
            </div>
        <% end %>
        <% if @error_discount_reused %>
            <div class="alert alert-danger">
              <strong><%= t('session.error_discount_reused') %></strong>
            </div>
        <% end %>
        <% if @error_code %>
            <div class="alert alert-danger">
              <strong><%= t('.code_error') %></strong>
            </div>
        <% end %>
        <input type="text" placeholder="Enter code" name="carrefour_code" value=""<%= params[:carrefour_code] %>">
        <input type="submit" class="btn green-bck white pad10 padlr25" value="<%= t('.valid') %>">
        <ul class="payment-cards">
          <li><%= image_tag "template/card-american-express-small.png" %></li>
          <li><%= image_tag "template/card-visa-small.png" %></li>
          <li><%= image_tag "template/card-master-small.png" %></li>
          <li><%= image_tag "template/card-atos-small.png" %></li>
          <li><%= image_tag "template/card-paypal-small.png" %></li>
          <li><%= image_tag "template/card-version-secured-small.png" %></li>
          <li><%= image_tag "template/card-norton-small.png" %></li>
        </ul>
        <p class="block100 text-left f13 mart15">Secured online transactions managed by Ingenico</p>
      </div>
  <% end %>
</div>

app/views/home/index.html.erb
<%= render :partial => 'home/index/carousel_public' %>
<%= render :partial => 'home/index/promo_film' if 1 == 0 && (!current_customer && params[:kind] == :normal) %>
<div id="services-wrap">
  <div class="wrap" id="vod-ppv">
    <h3><%= t ".unlinmited#{params[:kind] == :adult ? '_adult' : ''}" %></h3>
    <center>
        <%= link_to image_tag("#{I18n.locale}/#{t('.vod_unlimited_img')}#{params[:kind]==:adult ? '-adult' : ''}.gif", :size => '200x95', :alt => t('.vod_unlimited')), products_short_path(:package => t("routes.product.params.package.#{Moovies.packages.invert[@svod_id]}"), :tag => 2) %>
    </center>
    • <%= t ".unlinmited1#{params[:kind] == :adult ? '_adult' : ''}" %><br />
    • <%= t ".unlinmited2#{params[:kind] == :adult ? '_adult' : ''}" %><br />
    • <%= raw t ".unlinmited3#{params[:kind] == :adult ? '_adult' : ''}" %>
    <ul class="osc">
      <li><%= link_to t('.discover'), products_short_path(:package => t("routes.product.params.package.#{Moovies.packages.invert[@svod_id]}"), :tag => 2) %></li>
    </ul>
  </div>
  <div class="wrap" id="alacarte">
    <h3><%= t ".tvod#{params[:kind] == :adult ? '-adult' : ''}" %></h3>
    <center>
      <%= link_to image_tag("#{I18n.locale}/pay-per-view#{params[:kind]==:adult ? '-adult' : ''}.gif", :size => '200x95', :alt => 'pay per view'), products_short_path(:package => t("routes.product.params.package.#{Moovies.packages.invert[@tvod_id]}"), :tag => 2) %>
    </center>
    • <%= t ".tvod1#{params[:kind] == :adult ? '_adult' : ''}" %><br />
    • <%= t ".tvod2#{params[:kind] == :adult ? '_adult' : ''}" %><br />
    • <%= raw t ".tvod3#{params[:kind] == :adult ? '_adult' : ''}" %>
    <ul class="osc">
      <li><%= link_to t('.discover'), products_short_path(:package => t("routes.product.params.package.#{Moovies.packages.invert[@tvod_id]}"), :tag => 2) %></li>
    </ul>
  </div>
  <div class="wrap" id="apps">
    <h3><%= t '.multi' %></h3>
    <center>
      <%= link_to image_tag("#{I18n.locale}/video-on-demand#{params[:kind]==:adult ? '-adult' : ''}.gif", :size => '200x95', :alt => 'video on demand'), info_path(:page_name => t('routes.infos.params.vod')) %>
    </center>
    • <%= t '.multi1' %><br />
    • <%= t '.multi2' %><br />
    • <%= raw t '.multi3' %>
    <ul class="osc">
      <li><%= link_to t('.discover'), info_path(:page_name => t('routes.infos.params.vod')) %></li>
    </ul>
  </div>
  <div class="wrap" id="news">
    <h3 class="<%= I18n.locale %>"><%= t '.newsletter' %></h3>

    <%= form_for @newsletter do |f| %>
    <center>
        <%= f.error_messages :header_message => "", :message => "", :header_tag => :h3 %>
        <%= f.hidden_field :language_id, :value => Moovies.customer_languages[I18n.locale] %>
        <%= hidden_field_tag :promo, params[:code] %>
        <%= f.text_field :email, :size => 30, :value => 'Philippe@gmail.com' %>
    </center>
    • <%= t '.newsletter1' %><br />
    • <%= t '.newsletter2' %><br />
    • <%= raw t '.newsletter3' %><br />
    <ul class="osc">
      <li>
        <%= submit_tag t('.valid', :default => 'JE valide'), :id => 'newsletter_input' %>
      </li>
    </ul>
    <% end %>
    
  </div>
</div>
<%= render :partial => 'home/index/lists', :locale => {:type => 'hp'} %>

<!--   ==============   END MAIN CONTENT   ==============   -->

app/views/home/validation.html.erb
<div class="container white-bck">
    <div data-content="<%= t('orange_promo_banner_text_adult').html_safe %>" class="promo-image rwd-bck mart30" id="promo-image4" style="background-image: url('http://staging.plush.be/assets/promo_banner/adult2.jpg')">
        &nbsp;
    </div>
</div>
<div class="container white-bck dark-gray padb20">
  <h1 class="OpenSansCondensed f30 dark-gray pad0 text-center"><%= t('.title') %></h1>
  <div class="block100 cred-buttons center-block">
    <%= link_to validation_path(:valid => 1), :id => :yes, :class => "#{I18n.locale} btn center-block f16 violet-bck uppercase radius4 padtb15" do %>
        <div class="fa-stack">
          <i class="fa fa-circle-thin fa-stack-2x"></i>
          <span class="fa fa-stack-1x fa-inverse fa-plus18"></span>
        </div>
        <%= t('.over18') %>
    <% end %>
    <%= link_to t('.under18'), root_localize_path(:kind => nil), :id => :no, class: "btn center-block f16 thinrgray-bck gray uppercase radius4 padtb15 mart15" %>
    <p class="block100 mart5 text-left"><%= t('.warning').html_safe %></p>
  </div>
</div>

app/views/home/validation_old.html.erb
<div style="position:relative !important; margin: 20px auto;width:400px">
  <div class="popup validation">
    <div class="content">
              <div id="addwishlist_title" ><%= t('.title') %></div>
             
              <p align="center"><%= link_to t('.over18'), validation_path(:valid => 1), :id => :yes, :class => I18n.locale %></p>
              <p align="center"><%= link_to t('.under18'), root_localize_path(:kind => nil), :id => :no %></p>
      
                <div id="movix_explain">
                  <%= t('.warning').html_safe %>
                </div>
           
            </div>
           
  </div>
</div>