config/routes.rb
Moovies::Application.routes.draw do

  match "angular_test" => "angular_test#index"

  match "renew_monthly_credits_for_a_la_carte" => "renew_monthly_subscription#renew_monthly_credits_for_a_la_carte"
  match "social_activation" => "social_activation#activate"
  match '/auth/:provider/callback' => 'authentications#create'
  match 'canvas' => 'authentications#canvas'

  concern :productable do
    resources :products, :only => :index
  end

  root to: 'products#index'

  resource :ogone, :only => [:create]
  resource :home_products, :only => [:update, :edit]
  resource :list, :only => [:new, :create]

  match 'flag' => 'home#flag'
  resources :prospects, :only => [:create, :new]
  scope '(:kind)', :kind => /normal|adult/ do
    localized do
      devise_for :customers, :controllers => {
        :registrations => "customers/registrations",
        :sessions => "customers/sessions"#,
        #:passwords => "customers/passwords"
      }
      resources :customers do
        match 'newsletter' => 'customers#newsletter', :only => [:update]
        resource 'addresses', :only => [:edit, :update, :create]
        resource 'suspension', :only => [:new, :create, :destroy]
        resource 'promotion', :only => [:show, :edit]
        resource 'images', :only => [:create]
        resource :payment_methods, :only => [:edit, :update, :show]
        resources :reviews, :only => [:index]
      end
      match 'info/:page_name' => 'info#index', :as => :info
      match 'streaming_products/sample', :to => 'streaming_products#sample'
      resources :streaming_products, :only => [:show] do
        match 'language' => 'streaming_products#language'
        match 'subtitle' => 'streaming_products#subtitle'
        match 'versions' => 'streaming_products#versions'
      end
      resources :products, :only => [:show], constraints: { :id => /[0-9]+[0-9a-zA-Z\-_]*/ }
      resources :products, :only => [], constraints: { :product_id => /[0-9]+[0-9a-zA-Z\-_]*/ } do
        resource :rating, :only => :create
        resources :reviews, :only => [:new, :create]
        #resources :tokens, :only => [:new, :create]
        match 'step' => 'products#step'
        match 'awards'=> 'products#awards'
        match 'seen' => 'products#seen'
        match 'trailer' => 'products#trailer'
        match 'uninterested' => 'products#uninterested'
        match 'action' => 'products#action'
        match 'log' => 'products#log'
        match 'data' => 'products#data'
        match 'sign_up' => 'products#sign_up'
      end
      match 'products(/:package)(/:view_mode)' => 'products#index', :as => :products_short
      resources :phone_requests, :only => [:new, :create, :index]
      resources :actors, :only => [:index], concerns: :productable
      resources :directors, :only => [], concerns: :productable
    end
  end

  root_path = 'products#index'

  scope ':locale/(:kind)', :locale => /en|fr|nl/, :kind => /normal|adult/ do
    match 'orangesmsconfirm' => 'orangeconfirm#promotion'
  	match "carrefourbonus" => "carrefourbonus#plans"
    match "freetrial" => "freetrial#plans"
    match "photobox" => "photobox#plans"
    match 'carrefour' => 'home#carrefour'
    match 'belgium' => "home#belgium"
    match 'halloween' => "halloween#collection"
    resource :public_promotion, :only => [:edit, :update]
    match "/" => 'products#index', :as => :root_localize
    match "validation" => 'home#validation'
    match 'customers/promotion' => "customers#promotion"
    devise_for :customers, :controllers => {
        :registrations => "customers/registrations",
        :confirmations => "customers/confirmations"#,
        #:passwords => "customers/passwords"
    }, :as => :old_customers
    resources :customers, :as => :old_customer do
      match 'newsletter' => 'customers#newsletter', :only => [:update]
      resource 'addresses', :only => [:edit, :update, :create]
      resource 'suspension', :only => [:new, :create, :destroy]
      resource 'promotion', :only => [:show, :edit]
      resource 'images', :only => [:create]
      resource :payment_methods, :only => [:edit, :update, :show]
      resources :reviews, :only => [:index]
    end
    match 'info/:page_name' => 'info#index', :as => :info_old

    resources :products, :only => [:index, :show], :as => :old_products do
      resource :rating, :only => :create
      resources :reviews, :only => [:new, :create]
      resources :tokens, :only => [:new, :create]
      match 'awards'=> 'products#awards'
      match 'seen' => 'products#seen'
      match 'trailer' => 'products#trailer'
      match 'uninterested' => 'products#uninterested'
      match 'action' => 'products#action'
      match 'log' => 'products#log'
    end
    resources :phone_requests, :only => [:new, :create, :index], :as => :old_phone_requests
    match 'search/(:search)' => 'search#index', :as => :search
    resources :public_newsletters, :only => [:new, :create]
    resources :reviews, :only => :show do
      resource :review_rating, :only => :create
    end
    match "messages/urgent" => "messages#urgent"
    resources :messages
    resources :tickets do
      resources :message_tickets, :only => [:create]
    end
    resources :promotions, :only => [:show]
    post 'promotions/:id' => "promotions#create", :as => :promotion_canva
    resource :subscription, :only => [:update]
    resources :categories, :only => [:index], concerns: :productable
    resources :actors, :only => [:index], concerns: :productable, :as => :old_actors
    resources :directors, :only => [], concerns: :productable, :as => :old_directors
    resources :studios, :only => [:index], concerns: :productable
    get 'faq', :to => 'messages#faq'

    resources :steps, :only => [:show, :update]
    resources :watchlists, :as => :vod_wishlists
    match 'display_vod' => 'watchlists#display_vod'
    resource :search_filters, :only => [:update, :destroy]
    match 'streaming_products/sample', :to => 'streaming_products#sample', :as => :old_streaming_products_sample
    resources :streaming_products, :only => [:show], :as => :old_streaming_products do
      match 'language' => 'streaming_products#language'
      match 'subtitle' => 'streaming_products#subtitle'
      match 'versions' => 'streaming_products#versions'
    end
    get 'unsubscribe', :to => 'customers#unsubscribe'
    get 'back_to_tvod', :to => 'customers#back_to_tvod'
    #match ':id' => "promotions#show", :as => :promotion_localize, constraints: lambda { |request| Promotion.find_by_name(request.path_parameters[:id]) || 'samsung' }
    get ':id' => "promotions#show", :as => :promotion_localize, :id => /samsung|promotion/
    post ':id' => "promotions#create", :as => :promotion_localize, :id => /samsung|promotion/

  end


  get ':id' => "promotions#show", defaults: { format: 'choose' }, :as => :promotion, :id => /smarttv|radio_contact|samsung|nostalgie|playstation/, :as => :short_promotion
  post ':id' => "promotions#show", defaults: { format: 'choose' }, :as => :promotion, :id => /smarttv|radio_contact|samsung|nostalgie/, :as => :short_promotion
  resources :promotions, defaults: { format: 'choose' }, :only => [:show], :as => :root_promotion

  match "/404", :to => "errors#not_found"
  match "/500", :to => "errors#not_found"

end

app/controllers/canvas_controller.rb
class CanvasController < ApplicationController

  layout "canvas"
  
  before_filter :find_product, :except => [:index, :drop_cached]

  def index
    if params[:category_id] && params[:filters].nil? || (params[:filters] && params[:filters][:category_id].nil?)
      params[:filters] = Hash.new if params[:filters].nil?
      params[:filters][:category_id] = params[:category_id]
    end
    if params[:package] == t('routes.product.params.package.unlimited')
      params[:package] = Moovies.packages.invert[1]
    end
    if params[:package] == t('routes.product.params.package.tvod')
      params[:package] = Moovies.packages.invert[2]
    end
    if params[:filters] && params[:filters][:view_mode]
      params[:view_mode] = params[:package] == Moovies.packages.invert[2] || params[:package] == Moovies.packages.invert[5] ? "tvod_#{params[:filters][:view_mode]}" : "svod_#{params[:filters][:view_mode]}"
    end
    if params[:package] and !['unlimited', 'tvod', 'adult_unlimited', 'adult_tvod'].include?(params[:package])
      params[:package] = Moovies.packages.invert[1]
    end
    #unless Moovies.packages.include?(params[:package])
    #  params[:package] = Moovies.packages.invert[1]
    #end
    unless current_customer
      if params[:kind] == :adult
        @discount_top = Discount.find(Moovies.discount["catalogue_adult_#{I18n.locale}"])
      else
        @discount_top = Discount.find(Moovies.discount["catalogue_#{I18n.locale}"])
      end
    end
    @body_id = 'products_index'
    @body_class ='not_reload'
    params[:director_id] = params[:old_director_id] if params[:old_director_id]
    params[:actor_id] = params[:old_actor_id] if params[:old_actor_id]
    if params['actor_id']
      params[:filters] = Hash.new if params[:filters].nil?
      @people = Actor.find(params['actor_id'])
      params['actor_id'] = @people.id
    end
    if params['director_id']
      params[:filters] = Hash.new if params[:filters].nil?
      @people = Director.find(params['director_id'])
      params['director_id'] = @people.id
    end
    
    if params[:package] == Moovies.packages.invert[1]
      @meta_title = t('products.index.unlimited.meta_title')
      @meta_description = t('products.index.unlimited.meta_description')
    elsif params[:package] == Moovies.packages.invert[2]
      @meta_title = t('products.index.tvod.meta_title')
      @meta_description = t('products.index.tvod.meta_description')
    elsif !params[:actor_id].nil?
      @meta_title = t('products.index.actor.meta_title', :name => @people.name)
      @meta_description = t('products.index.actor.meta_description', :name => @people.name)
    elsif !params[:director_id].nil?
      @meta_title = t('products.index.director.meta_title', :name => @people.name)
      @meta_description = t('products.index.director.meta_description', :name => @people.name)
    end
    @source = WishlistSource.wishlist_source(params, @wishlist_source)
    @vod_wishlist = current_customer.products.collect(&:products_id) if current_customer
    @countries = ProductCountry.visible.ordered
      if params[:package].nil? && params[:concerns] != :productable && params[:belgium].blank?
        new_params = session[:sexuality] == 0 ? params.merge(:per_page => 50, :country_id => session[:country_id], :hetero => 1, :includes => ["descriptions_#{I18n.locale}", 'vod_online_be']) : params.merge(:per_page => 50, :country_id => session[:country_id], :includes => ["descriptions_#{I18n.locale}", 'vod_online_be'])
        tvod_package_id = params[:kind] == :adult ? 5 : 2
        svod_package_id = params[:kind] == :adult ? 4 : 1
        @tvod_last =        Product.filter(nil, new_params.merge(:view_mode => 'tvod_last_added',  :package => Moovies.packages.invert[tvod_package_id]))
        @tvod_soon =        Product.filter(nil, new_params.merge(:view_mode => 'tvod_soon', :without_series =>1, :package => Moovies.packages.invert[tvod_package_id]))

        @tvod_best_rating = Product.filter(nil, new_params.merge(:view_mode => 'tvod_best_rated',  :package => Moovies.packages.invert[tvod_package_id]))
        @tvod_most_view =   Product.filter(nil, new_params.merge(:view_mode => 'tvod_most_viewed', :package => Moovies.packages.invert[tvod_package_id]))
        @tvod_last_chance = Product.filter(nil, new_params.merge(:view_mode => 'tvod_last_chance', :package => Moovies.packages.invert[tvod_package_id]))
        @svod_last =        Product.filter(nil, new_params.merge(:view_mode => 'svod_last_added',  :package => Moovies.packages.invert[svod_package_id]))
        @svod_best_rating = Product.filter(nil, new_params.merge(:view_mode => 'svod_best_rated',  :package => Moovies.packages.invert[svod_package_id]))
        @svod_most_view =   Product.filter(nil, new_params.merge(:view_mode => 'svod_most_viewed', :package => Moovies.packages.invert[svod_package_id]))
        #@svod_last_chance = Product.filter(nil, new_params.merge(:view_mode => 'svod_last_chance', :package => Moovies.packages.invert[params[:kind] == :adult ? 4 : 1]))
        @top = Product.joins(:lists).includes("descriptions_#{I18n.locale}", 'vod_online_be').where("lists.#{I18n.locale} = 1").order("lists.id desc").limit(25)
      else
        new_params = params.merge(:per_page => 25, :country_id => session[:country_id], :includes => [ "descriptions_#{I18n.locale}", 'vod_online_be'])
        new_params = new_params.merge(:hetero => 1) if session[:sexuality] == 0
        @products = Product.filter_online(nil, new_params)
        if params[:filters]
          @selected_countries = ProductCountry.where(:countries_id => params[:filters][:country_id]) 
          @languages = Language.by_language(I18n.locale).find(params[:filters][:audio].reject(&:empty?)).collect(&:name).join(', ') if Product.audio?(params[:filters][:audio])
          @subtitles = Subtitle.by_language(I18n.locale).find(params[:filters][:subtitles].reject(&:empty?)).collect(&:name).join(', ') if Product.subtitle?(params[:filters][:subtitles])
        end
      end
    #else
    #  
    #  @filter = view_context.get_current_filter({})
    #  new_params = session[:sexuality] == 0 ? params.merge(:per_page => 15, :country_id => session[:country_id], :hetero => 1) : params.merge(:per_page => 15, :country_id => session[:country_id])
    #  @products = Product.filter(@filter, new_params)
    #end
    @target = cookies[:endless] == 'deactive' ?  '_self' : '_blank'
    @carousels = Landing.hit.by_language(I18n.locale).not_expirated
    
    if params[:endless]
      cookies.permanent[:endless] = params[:endless]
    end
    if params[:display]
      cookies.permanent[:display] = params[:display]
    end
    @rating_color = params[:kind] == :adult ? :pink : :white
    if request.xhr?
      render :layout => false
    end
      
  end

private
  def find_product
    if !params[:recommendation].nil?
      @source = params[:recommendation]
    elsif params[:source]
      @source = params[:source]
    else
      @source = @wishlist_source[:elsewhere]
    end
    begin
      if params[:id]
        id = params[:id]
      elsif params[:old_product_id]
        id = params[:old_product_id]
      else
        id = params[:product_id]
      end
      if Rails.env == "production"
        if params[:kind] == :adult
          @product = Product.adult_available.find(id)
          @rating_color = :pink
        else
          @product = Product.normal_available.find(id)
          @rating_color = :white
        end
      else
        if params[:kind] == :adult
          @product = Product.find(id)
          @rating_color = :pink
        else
          @product = Product.find(id)
          @rating_color = :white
        end
      end
    rescue ActiveRecord::RecordNotFound
      msg = "product not found"
      logger.error(msg)
      flash[:notice] = msg
      redirect_to products_short_path
    end
  end

end

app/views/canvas/index/_all.html.erb
  <div class="loading_bar" style="display:none"><%= image_tag 'loading.gif' %></div>
  <div id="maincontent" >
  <div id='filter_layout'>
  <%= render :partial => 'layouts/filters_online', :locals => {:selected_countries => @selected_countries, :languages => @languages, :subtitles => @subtitles }%>
  </div>
  <h1 class="ttl">&nbsp;</h1>
  <%= render :partial => 'products/index/image', :locals => {:people => @people} if @people %>
  <% if cookies[:display] == 'list' %>
    <div class="selected-Expanded"  >list</div> <%= link_to t('.jacket'), params.merge(:display => 'jacket', :kind => (params[:kind] == :normal ? nil : params[:kind]), :page => nil), :class => 'Grid' %>
  <% else %>
    <%= link_to t('.list'), params.merge(:display => 'list', :kind => (params[:kind] == :normal ? nil : params[:kind]), :page => nil), :class => 'Expanded' %> <div class="selected-Grid">jacket</div>
  <% end %>
  <!--   ==============   MOVIES   ==============   -->
  <% if cookies[:endless] == 'deactive' %>
    <%= link_to t('products.index.endless_active'), params.merge(:endless => 'active', :kind => (params[:kind] == :normal ? nil : params[:kind]), :page => nil), :class => "endless" %>
  <% else %>
    <%= link_to t('products.index.endless_deactive'), params.merge(:endless => 'deactive', :kind => (params[:kind] == :normal ? nil : params[:kind]), :page => nil), :class => "endless" %>
  <% end %>
  <div id="products">
    <%= render :partial => 'products/index/sorting' %>
    <%= render :partial => cookies[:display] == 'list' ? 'products/index/movie_details' : 'products/index/movie_details_jacket', :collection => @products, :locals => {:target => @target} %>
  </div>
  <div id='pagination_content'>
      <%= render :partial => 'products/index/pagination', :locals => {:item => @products} %>
  </div>
  <%= t(products_index_description, :link_abo => info_path(:page_name => t('routes.infos.params.vod')), :link_svod => (params[:kind] == :adult ? products_short_path(:package => Moovies.packages.invert[4]) : products_short_path(:package => t("routes.product.params.package.#{Moovies.packages.invert[1]}"))), :link_tvod => (params[:kind] ==  :adult ? products_short_path(:package => Moovies.packages.invert[5]) : products_short_path(:package => t("routes.product.params.package.#{Moovies.packages.invert[2]}")))).html_safe %>

  <!--   ==============   END MOVIES   ==============   -->
  </div>
<%= render :partial => 'products/index/filters_online', :locals => { :countries => @countries} %>  

app/views/canvas/index/_hp.html.erb
<div class="loading_bar" style="display:none"><%= image_tag 'loading.gif' %></div>
<div id="maincontent" >
  <div id='filter_layout'></div>
  <div id="products">
     <div class="tvod"><h2><%= t('.alacarte') %> :</h2>
       <%= render :partial => 'products/index/hp_list', :locals => {:data => @top, :title => :top, :type => nil, :view_mode => nil, :source => 64, :belgium => nil} if @top.size > 5 && params[:kind] != :adult%>

       <%= render :partial => 'products/index/hp_list', :locals => {:data => @tvod_soon, :title => :tvod_soon, :type => :tvod, :view_mode => :soon, :source => 14, :belgium => nil} if @tvod_soon.size > 5 %>
       <%= render :partial => 'products/index/hp_list', :locals => {:data => @tvod_last, :title => :tvod_last, :type => :tvod, :view_mode => :last_added, :source => 65, :belgium => nil} if @tvod_last.size > 5 %>
       <%= render :partial => 'products/index/hp_list', :locals => {:data => @tvod_best_rating, :title => :tvod_best_rating, :type => :tvod, :view_mode => :best_rated, :source => 66, :belgium => nil} if @tvod_best_rating.size > 5 %>
       <%= render :partial => 'products/index/hp_list', :locals => {:data => @tvod_most_view, :title => :tvod_most_view, :type => :tvod, :view_mode => :most_viewed, :source => 67, :belgium => nil} if @tvod_most_view.size > 5 %>
       <%= render :partial => 'products/index/hp_list', :locals => {:data => @tvod_last_chance, :title => :tvod_last_chance, :type => :tvod, :view_mode => :last_chance, :source => 68, :belgium => nil} if @tvod_last_chance.size > 5 %>
    </div> 
    <div class="svod"><h2><%= t('.unlimited') %> :</h2>
      <%= render :partial => 'products/index/hp_list', :locals => {:data => @svod_last, :title => :svod_last, :type => :svod, :view_mode => :last_added, :source => 65, :belgium => nil} if @svod_last.size > 5 %>
      <%= render :partial => 'products/index/hp_list', :locals => {:data => @svod_best_rating, :title => :svod_best_rating, :type => :tvod, :view_mode => :best_rated, :source => 66, :belgium => nil} if @svod_best_rating.size > 5%>
      <%= render :partial => 'products/index/hp_list', :locals => {:data => @svod_most_view, :title => :svod_most_view, :type => :svod, :view_mode => :most_viewed, :source => 67, :belgium => nil} if @svod_most_view.size > 5 %>
   </div> 
  </div>
</div>
<%= render :partial => 'products/index/filters_online', :locals => { :countries => @countries} %>  
<div id='pagination_content'></div>

app/views/canvas/index/_hp_list.html.erb
<% package_id = type == :svod ? (params[:kind] == :adult ? 4 : 1) : (params[:kind] == :adult ? 5 : 2) %>
<div id="ca-container" class="ca-container">
  <div class="title"><%= t(".title_#{title}")%>
    <%= link_to t(".more"), products_short_path(:package => Moovies.packages.invert[package_id], 'filters[view_mode]' => view_mode), :class => :small if !type.nil? %>
    <%= link_to t(".more"), products_short_path('belgium' => belgium, :source => source), :class => :small if !belgium.nil? %>

  </div>
  <div class="ca-wrapper">
    <%= render :partial => 'products/detail2', :collection => data, :locals => {:source => source, :view_mode  => view_mode } %>
  </div>
</div>

app/views/canvas/index/_movie_details.html.erb
<% product = movie_details %>
<% data = product.description_data(true) %>
<% product_title = data[:title] %>
<% product_image = data[:image] %>
<% product_description =  data[:description] %>
<% path = product_path(:id => product.to_param, :source => @source, :response_id => @response_id) %>
<div class="movie-wrap">
  <div class="movie-ttl">
    <h3><%= link_to product.smart_title, path, :target => target %></h3>
    <div class="stars vote" id="rating-stars-<%= product.id %>" product_id="<%= product.id %>">
      <%= render :partial => 'products/rating', :locals => {:product => product, :background => :white, :size => :long, :source => @source, :response_id => @response_id} %>
    </div>
  </div><!-- .movie-ttl -->
  <div class="movie-content">
    <div class="movie-descr">
      <div class="cast">
        <% if !product.actors.empty?  %>
        <h4><%= t '.actors' %></h4>
        <p><%= product.actors.collect{|actor| link_to actor.name, actor_products_path(:actor_id => actor.to_param)}.join(', ').html_safe %></p>
        <% end %>
        <% if product.director && !product.adult? %>
          <h4><%= t '.director' %></h4>
          <p><%= link_to product.director.name, director_products_path(:director_id => product.director.to_param) %></p>
        <% end %>
        <% if product.adult? && product.studio %>
          <h4><%= t '.studio' %></h4>
          <p><%= link_to product.studio.name, studio_products_path(:studio_id => product.studio.to_param) %></p>
        <% end %>
      </div>
      <p><%= truncate_html(product_description.text, :length => 300) if product_description %></p>
      
      <%= link_to(t('.more'), path, :target => target, :class => 'osc') %>
      <div class="thumb-wrap">
        <%= "<span class='hd'></span>".html_safe if product.hd?(session[:country_id]) %>
        <%= link_to path, :target => target, :class => :cover, :alt => product_title do %>
          <%= product_image_tag product_image, :width => 100 %>
        <% end %>
      </div>
      
      <!--<span class="hd"></span>-->
    </div><!-- .movie-descr -->

    <div class="oters">
      <ul class="lang">
        <li class="left dark osc"><%= product.public.name if product.public %></li>
        <%= bubbles(product).html_safe %>
      </ul>

      <div class="links" id="seen-uninterested-<%= product.to_param %>">
        <%= render :partial => 'products/show/seen_uninterested', :locals => {:product => product, :source => @source, :response_id => @response_id} if current_customer %>
      </div>

      <ul class="btns osc">
        <% unless product.series? %>
        <li>
          <%= render :partial => 'products/streaming',  :locals => {:product => product, :source => @source, :popup => true} %>
        </li>
        <li>
          <%= render :partial => 'products/vod_list',  :locals => {:product => product, :source => @source, :response_id => @response_id} %>
        </li>
        <% end %>
        <% if product.trailer? %>
        <li>
          <%= link_to(t('.trailer'), product_trailer_path(:product_id => product.to_param, :source => @source, :response_id => @response_id), :class => 'trailer', :target => :_blank) %>
        </li>
        <% end %>

      </ul>
    </div><!-- .oters -->
  </div><!-- .movie-content -->
</div><!-- .movie-wrap -->

app/views/canvas/index/_pagination.html.erb
<%= will_paginate item, :class => "products-pagination osc #{cookies[:endless] == 'deactive' ? 'deactive' : 'active'}", :id => :pagination, :previous_label => '«', :next_label => '»', :params => {:kind => params[:kind] == :normal ? nil : params[:kind]} %>

app/views/canvas/index/_sorting.erb
<div class="bysort">
  <div class="bysort_title"><%= t '.title'%> : </div>
  <div class="bysort_choice">
    <% var = params[:sort] ? params[:sort].to_sym : :normal %>
    <%= form_for(:product, :url => request.fullpath, :html => { :method => :get, :id => :sort_form  } ) do |f| %>
      <%= hash_to_hidden_fields(params.merge(:page => nil, :sort => nil)) %>
      <%= select_tag(:sort, options_for_select(sort_collection_for_select, var), { :onchange => '$("#sort_form").submit()'}) %>
    <% end %>
  </div>
  <div style="clear:both"></div>
</div>